# Generated by Django 5.0 on 2023-12-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countscope", "0002_countscope_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countscope",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
    ]
