# Generated by Django 5.0 on 2023-12-29 23:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("countscope", "0002_countscope_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="countscope",
            name="slug",
        ),
    ]
