# Generated by Django 5.0 on 2023-12-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countscope", "0002_remove_countscope_imageurl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="countscope",
            name="isActive",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="countscope",
            name="slug",
            field=models.SlugField(blank=True, default="", unique=True),
        ),
    ]
