# Generated by Django 5.0 on 2023-12-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countscope", "0003_alter_countscope_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="countscope",
            name="id",
        ),
        migrations.AlterField(
            model_name="countscope",
            name="slug",
            field=models.SlugField(default="", primary_key=True, serialize=False),
        ),
    ]
