# Generated by Django 5.0 on 2024-01-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countscope", "0003_countscope_isactive_alter_countscope_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countscope",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
