# Generated by Django 5.0 on 2024-01-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countscope", "0004_alter_countscope_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countscope",
            name="isActive",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
