# Generated by Django 5.0 on 2024-01-03 21:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countscope", "0005_alter_countscope_isactive"),
    ]

    operations = [
        migrations.AddField(
            model_name="countscope",
            name="subtitle",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="countscope",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="countscope",
            name="isActive",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="countscope",
            name="slug",
            field=models.SlugField(blank=True, default="", null=True, unique=True),
        ),
    ]
